version: "1.0"
stages:
  - "prep"
  - "sync"
  - "test"

steps:

  # Add pre-deployment test steps here (cluster/app heath, etc)

  argocd_sync:
    title: Sync ArgoCD app and wait
    stage: sync
    type: argocd-sync
    arguments:
      context: '${{ARGOCD_AGENT}}'
      app_name: '${{ARGOCD_APP_NAME}}'
      wait_healthy: true
      # debug: true
      additional_flags:
        - '--grpc-web'
        # - '--loglevel debug'

  # Add post-deployment or canary promotion steps here
  