apiVersion: v2
name: all-services
description: A Helm chart for Kubernetes
type: application
version: 0.1.8
dependencies:
  - name: buslog
    version: "1.4.2"
    repository: "cm://h.cfcr.io/codefreshdemo/default"
  - name: ctrlr
    version: "1.3.2"
    repository: "cm://h.cfcr.io/codefreshdemo/default"
  - name: flask-ui
    version: "1.2.3"
    repository: "cm://h.cfcr.io/codefreshdemo/default"
